apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: secure-routing
    annotations:
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-secret: mycredentials
        nginx.ingress.kubernetes.io/auth-realm: "Realm Example Text"
spec:
    rules:
        - host: k8s.queue.transier.industries
          http:
            paths:
                - path: /
                  backend:
                    serviceName: fleetman-queue
                    servicePort: 8161

