kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: new-joiner
    namespace: default
rules:
    - apiGroups: ["", "apps"] # core api group (v1) and apps (for deployments)
      resources: ["*"] # pods, services, deployments
      verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: add-user-to-new-joiner
    namespace: default
subjects:
    - kind: User
      name: chico-linux-login-name
roleRef:
    kind: Role
    name: new-joiner
    apiGroup: rbac.authorization.k8s.io
