apiVersion: batch/v1
kind: Job
metadata:
    name: python-example
spec:
    template:
        spec: #Pod
            containers:
            - name: python-example
              image: python:slim
              command: ["python"]
              args: ["-c", "import time; print('starting'); time.sleep(15); print('done');"]
            restartPolicy: Never
    backoffLimit: 2
